version: "3.7"
services:
  frontend:
    image: ghcr.io/jiyeon12345/photolink-web-vue:latest
    container_name: docker-frontend-deploy-server
    networks:
      - app

networks:
  app:
    driver: bridge
